const fs = require('fs')
const { fileURLToPath, pathToFileURL } = require('url')

const HEADER = '// This runner is auto-generated by Brittle'
const IMPORT = /^const test = \(await import\((['"])brittle\1\)\)\.default;?$/
const FUNCTION = /^async\s+function runTests\s*\(\s*\)\s*\{$/
const LOAD = /^(if \(isBare\) )?await test\.load\(import\.meta\.resolve\((['"])([^'"]+)\2\)\);?$/

module.exports = function expand(file, { bare }) {
  const specifiers = parse(fs.readFileSync(file, 'utf8'))
  if (specifiers === null) return [file]

  const files = []
  for (const { guarded, specifier } of specifiers) {
    if (guarded && !bare) continue
    const resolved = resolve(file, specifier)
    if (resolved === null) return [file]
    files.push(resolved)
  }
  return files.length > 0 ? files : [file]
}

// Recognize only the small declarative wrapper emitted by brittle-make-test.
// Anything else must run as the original file so setup and inline tests remain
// in the same process and unsupported control flow is never guessed at.
function parse(source) {
  const lines = source.split(/\r?\n/)
  let i = 0

  const blank = () => {
    while (i < lines.length && lines[i].trim() === '') i++
  }
  const line = (pattern) => {
    if (i >= lines.length || !pattern.test(lines[i].trim())) return false
    i++
    return true
  }

  blank()
  if (lines[i]?.trim() === HEADER) i++
  blank()
  if (!line(/^await runTests\(\);?$/)) return null
  blank()
  if (!line(FUNCTION)) return null
  blank()
  if (!line(IMPORT)) return null
  blank()
  if (!line(/^test\.pause\(\);?$/)) return null

  blank()
  let hasIsBare = false
  if (line(/^const isBare = typeof Bare !== (['"])undefined\1;?$/)) {
    hasIsBare = true
    blank()
  }

  const loads = []
  let hasGuardedLoad = false
  while (i < lines.length) {
    const current = lines[i].trim()
    if (current === '') {
      blank()
      continue
    }
    if (current === 'test.resume()' || current === 'test.resume();') break

    const match = LOAD.exec(current)
    if (!match) return null
    if (match[1]) hasGuardedLoad = true
    loads.push({ guarded: !!match[1], specifier: match[3] })
    i++
  }

  if (!line(/^test\.resume\(\);?$/)) return null
  blank()
  if (!line(/^}$/)) return null
  blank()
  if (i !== lines.length) return null
  if (hasGuardedLoad && !hasIsBare) return null
  return loads
}

function resolve(file, specifier) {
  // Keep the accepted subset equivalent to import.meta.resolve for relative
  // file specifiers. A process can only be started with a filesystem path.
  // The recognizer intentionally does not decode JavaScript string escapes.
  // Reject them rather than resolving a different path from the runner.
  if (
    specifier.includes('\\') ||
    (specifier !== '.' &&
      specifier !== '..' &&
      !specifier.startsWith('./') &&
      !specifier.startsWith('../'))
  ) {
    return null
  }

  try {
    const url = new URL(specifier, pathToFileURL(file))
    if (url.protocol !== 'file:' || url.hostname || url.search || url.hash) return null
    return fileURLToPath(url)
  } catch {
    return null
  }
}
